import hashlib
import logging
import shutil
import subprocess
import time
from collections.abc import Iterable
from pathlib import Path
from tempfile import TemporaryDirectory

from download_examples import EXAMPLES_PATH, download_gifs

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

TEMPLATE_FILE = "README.tmpl.md"
CLI_USAGE_MARKER = "{{ cli_usage }}"
GIF_BENCH_MARKER = "{{ gif_bench }}"
OUTPUT_FILE = "README.md"
BASE_DOWNLOAD_URL = (
    "https://github.com/waresnew/gif-compressor/releases/download/examples/"
)


def main() -> None:
    check_requirements()
    logger.info("Populating build cache")
    subprocess.run(
        ["cargo", "build", "--release"],
        check=True,
        capture_output=True,
    )
    output = None
    with (Path.cwd() / TEMPLATE_FILE).open("r") as template:
        output = template.read()
    output = "<!-- This file is autogenerated -->\n\n" + output
    logger.info("Generating CLI help message")
    output = output.replace(CLI_USAGE_MARKER, gen_cli_usage())
    logger.info("Generating GIF examples")
    output = output.replace(GIF_BENCH_MARKER, gen_gif_bench())
    logger.info("Writing to %s", Path.cwd() / OUTPUT_FILE)
    with (Path.cwd() / OUTPUT_FILE).open("w") as file:
        file.write(output)
    logger.info("Done")


def check_requirements() -> None:
    if shutil.which("gifsicle") is None:
        err = "gifsicle was not found in PATH"
        raise RuntimeError(err)
    if shutil.which("cargo") is None:
        err = "cargo was not found in PATH"
        raise RuntimeError(err)
    if not EXAMPLES_PATH.exists():
        logger.warning("GIF examples are not downloaded locally, downloading now...")
        download_gifs()


def gen_gif_bench() -> str:
    gifsicle_args = ["-O3", "--lossy=200"]

    def run_gifsicle(files: Iterable[Path], tmp_dir: Path) -> dict[str, float]:
        """
        synchronous bc benchmarking
        """
        logger.info("Running gifsicle on GIFs")
        ans = {}
        for file in files:
            start = time.perf_counter()
            logger.info("Running gifsicle on %s", file.name)
            subprocess.run(  # noqa: S603
                [
                    "gifsicle",
                    *gifsicle_args,
                    file,
                    "-o",
                    tmp_dir / f"{file.name}.gifsicle",
                ],
                check=True,
            )
            ans[file.name] = time.perf_counter() - start
        return ans

    def run_program(
        files: Iterable[Path],
        tmp_dir: Path,
    ) -> dict[str, float]:
        """
        synchronous bc benchmarking
        """
        logger.info("Running program on GIFs")

        ans = {}
        for file in files:
            start = time.perf_counter()
            logger.info("Running program on %s", file.name)
            subprocess.run(  # noqa: S603
                [
                    "cargo",
                    "run",
                    "--release",
                    "--",
                    "-i",
                    file,
                    "-o",
                    tmp_dir / f"{file.name}.output",
                ],
                check=True,
            )
            ans[file.name] = time.perf_counter() - start
            expected_hash = hashlib.file_digest(
                Path.open(
                    EXAMPLES_PATH / f"{file.name.removesuffix('.gif') + '_output.gif'}",
                    "rb",
                ),
                "sha256",
            ).digest()
            actual_hash = hashlib.file_digest(
                Path.open(tmp_dir / f"{file.name}.output", "rb"),
                "sha256",
            ).digest()
            if actual_hash != expected_hash:
                msg = f"{file.name}'s program output did not match expected output"
                raise ValueError(msg)
        return ans

    with TemporaryDirectory() as tmp_dir_string:
        tmp_dir = Path(tmp_dir_string)
        input_files = [
            x
            for x in EXAMPLES_PATH.iterdir()
            if x.is_file() and not x.name.endswith("_output.gif")
        ]
        gifsicle_timings = run_gifsicle(input_files, tmp_dir)
        program_timings = run_program(input_files, tmp_dir)
        rows: list[tuple[float, str]] = []
        for input_file in input_files:
            input_size = input_file.stat().st_size / 1000000
            gifsicle_size = (
                tmp_dir / f"{input_file.name}.gifsicle"
            ).stat().st_size / 1000000
            expected_output_file_name = (
                input_file.name.removesuffix(".gif") + "_output.gif"
            )
            output_size = (
                EXAMPLES_PATH / expected_output_file_name
            ).stat().st_size / 1000000

            gifsicle_compression = round(
                (gifsicle_size - input_size) * 100 / input_size,
            )
            output_compression = round((output_size - input_size) * 100 / input_size)

            output_url = BASE_DOWNLOAD_URL + expected_output_file_name
            input_url = BASE_DOWNLOAD_URL + input_file.name

            rows.append(
                (
                    input_size,
                    f"""
<tr>
<td width="45%">{input_size:.1f} MB <br><img src="{input_url}" alt="{input_url}" width="100%"></td>
<td width="10%">{gifsicle_size:.1f} MB ({gifsicle_compression:+d}%) in {gifsicle_timings[input_file.name]:.1f}s</td>
<td width="45%">{output_size:.1f} MB ({output_compression:+d}%) in {program_timings[input_file.name]:.1f}s <br><img src="{output_url}" alt="{output_url}" width="100%"></td>
</tr>
                """,  # noqa: E501
                ),
            )

        rows.sort()
        return "\n".join(
            [
                f"""
The file size and runtime are compared to [gifsicle](https://github.com/kohler/gifsicle) with the `{" ".join(gifsicle_args)}` arguments on the same input.

<table>
<tr>
<th width="45%">Input</th>
<th width="10%">Gifsicle</th>
<th width="45%">Program Output</th>
</tr>
        """,  # noqa: E501
                *[row[1] for row in rows],
                "</table>",
            ],
        )


def gen_cli_usage() -> str:
    output = (
        subprocess.run(
            ["cargo", "run", "--release", "--", "-h"],
            check=True,
            capture_output=True,
        )
        .stdout.decode()
        .strip()
    )
    return f"""
```
{output}
```
"""


if __name__ == "__main__":
    main()
